FROM sonatype/nexus3:{{ nexus_version }}

USER root

ENV NEXUS_HOME="/opt/sonatype/nexus"
ENV NEXUS_PLUGINS ${NEXUS_HOME}/system

WORKDIR "${NEXUS_HOME}"

ENV KEYCLOAK_PLUGIN_VERSION {{ keycloak_plugin_version }}
ENV KEYCLOAK_PLUGIN org/github/flytreeleft/nexus3-keycloak-plugin/${KEYCLOAK_PLUGIN_VERSION}

ADD nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar ${NEXUS_PLUGINS}/${KEYCLOAK_PLUGIN}.jar

RUN chmod 644 ${NEXUS_PLUGINS}/${KEYCLOAK_PLUGIN}.jar
RUN chown nexus ${NEXUS_PLUGINS}/${KEYCLOAK_PLUGIN}.jar
RUN echo "reference\\:file\\:${KEYCLOAK_PLUGIN}.jar = 200" >> ${NEXUS_HOME}/etc/karaf/startup.properties

RUN cat ${NEXUS_HOME}/etc/karaf/startup.properties
RUN cat ${NEXUS_HOME}/etc/karaf/startup.properties

RUN echo "nexus.scripts.allowCreation=true" >> ${NEXUS_HOME}/etc/nexus-default.properties

EXPOSE 5000 8081 8443
USER nexus

CMD ["bin/nexus", "run"]