FROM {{ java_base_image }}

ENV KAFKA_VERSION={{ kafka_version }}
ENV SCALA_VERSION={{ scala_version }}
ENV KAFKA_HOME={{ kafka_home }}
ENV PATH=${PATH}:${KAFKA_HOME}/bin
ENV KAFKA_CONFIG=${KAFKA_HOME}/config/kraft/server.properties
ENV KAFKA_LOGS_PATH=${KAFKA_HOME}/var/log/kafka
ENV KAFKA_CONSOLE_LOG=/var/log/kafka/helk-kafka.log
ENV KAFKA_GID=910
ENV KAFKA_UID=910
ENV KAFKA_USER=kafka

LABEL name="kafka" version=${KAFKA_VERSION}

# Install Kafka
RUN apt-get update && apt-get -y install unzip wget \
&& wget -O /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
&& tar xvzf /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt \
&& rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
&& ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} ${KAFKA_HOME} \
&& rm -rf /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz



WORKDIR $KAFKA_HOME

COPY entrypoint.sh /

RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT ["/entrypoint.sh"]
